# ---------------------------------------------------------
# Configuration file for http://travis-ci.org/#!/karmi/tire
# ---------------------------------------------------------

language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - ree

script: "bundle exec rake test"

before_install:
  - sudo service elasticsearch start

notifications:
  disable: true
